### ISSUE TITLE
Handle requests from clients

### ISSUE THREAD

**Issue by Nodrex** [shalva97/keyFusion#15]
We need Queue for clients in order to server images properly

**Comment by Nodrex** [comment]
SD Api does not handles multiple requests. here is error when requested image generation multiple times:

```
Started working on [8cee9dcd-0c65-487f-856c-fefea3880bad] ts[1677430348731]
2023-02-26 20:52:31.328 [eventLoopGroupProxy-4-2] DEBUG ktor.application - 200 OK: GET - /. Exception class java.net.SocketTimeoutException: timeout]
java.net.SocketTimeoutException: timeout
	at okio.SocketAsyncTimeout.newTimeoutException(JvmOkio.kt:147)
	at okio.AsyncTimeout.access$newTimeoutException(AsyncTimeout.kt:158)
	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:337)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:427)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:320)
	at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at com.codecraft.ai.api.plugins.RoutingKt.go(Routing.kt:72)
	at com.codecraft.ai.api.plugins.RoutingKt$configureRouting$1$1.invokeSuspend(Routing.kt:34)
```
First is log before request is sent from our API to SD API and last line `Routing.kt:34` is our file so here we can see that `SocketTimeoutException` occured cause SD was working on previous request.

So we need to handle multiple requests ourselvs

**Comment by Nodrex** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/8141#discussioncomment-5115720
